name: Make All of Selfie

on:
  push:
    branches: [ master ]
    paths:
    - '**.c'
    - 'Makefile'
    - '**.py'
    - 'Dockerfile'
    - '.dockerignore'
    - '.github/workflows/selfie.yml'
  pull_request:
    branches: [ master ]
    paths:
    - '**.c'
    - 'Makefile'
    - '**.py'
    - 'Dockerfile'
    - '.dockerignore'
    - '.github/workflows/selfie.yml'
  schedule:
    # trigger fridays at 12am
    - cron: '0 0 * * 5'

jobs:
  make-all-of-selfie:
    name: Make all of selfie and run autograder baseline
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout selfie
      uses: actions/checkout@v2
    - name: Make all
      run: make all
    - name: Use Python 3.7.x
      uses: actions/setup-python@v1
      with:
        python-version: "3.7.x"
    - name: Run autograder baseline
      run: make grade

  run-selfie-on-docker:
    name: Run selfie on docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout selfie
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -t cksystemsteaching/selfie .
    - name: Run selfie on docker
      run: |
        docker run cksystemsteaching/selfie make all
        docker run cksystemsteaching/selfie make grader
        docker run cksystemsteaching/selfie make grade
        docker run cksystemsteaching/selfie make assemble
        docker run cksystemsteaching/selfie make spike
        docker run cksystemsteaching/selfie make qemu
        docker run cksystemsteaching/selfie make boolector
        docker run cksystemsteaching/selfie make btormc