name: selfie

on:
  push:
    branches: [ master ]
    paths:
    - '**.c'
  pull_request:
    branches: [ master ]
    paths:
    - '**.c'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: make all