name: Make All of Selfie

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '**.md'
    - '**.txt'
    - 'docs'
    - 'AUTHORS'
    - 'LICENSE'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - '**.md'
    - '**.txt'
    - 'docs'
    - 'AUTHORS'
    - 'LICENSE'
  schedule:
    # trigger fridays at 12am
    - cron: '0 0 * * 5'

jobs:
  make-all-of-selfie:
    name: Make all of selfie and run autograder baseline
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout selfie
      uses: actions/checkout@v2
    - name: Make all
      run: make all
    - name: Use Python 3.7.x
      uses: actions/setup-python@v1
      with:
        python-version: "3.7.x"
    - name: Run autograder baseline
      run: make grade

  run-selfie-on-docker:
    name: Run selfie on docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout selfie
      uses: actions/checkout@v2
    - name: Run selfie on docker
      uses: cksystemsteaching/selfie@master