name: selfie

on:
  push:
    branches: [ master ]
    paths:
    - '**.c'
    - '**.py'
    - 'Dockerfile'
    - 'Makefile'
    - '.github/workflows/selfie.yml'
  pull_request:
    branches: [ master ]
    paths:
    - '**.c'
    - '**.py'
    - 'Dockerfile'
    - 'Makefile'
    - '.github/workflows/selfie.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make all
      run: make all