name: selfie

on:
  push:
    branches: [ master ]
    paths:
    - '**.c'
    - 'Makefile'
  pull_request:
    branches: [ master ]
    paths:
    - '**.c'
    - 'Makefile'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make all
      run: make all
